### ISSUE TITLE
数据处理dataloader问题请教

### ISSUE THREAD

**Issue by ahukmr** [YangLiangwei/DGRec#11]
在dataloader中，加载训练集构建graph_data时，是按照训练集读取，但训练集中的数据是1,1550
1,1691
1,1259
1,5365
1,2558
1,2894
1,1835
1,4883
1,1739
1,3222
1,4428，我的理解这里的物品id不是按照从小到大有序排列的，而在加载类别信息时，读取category数据集时物品是按照id从小到大有序排列的，而代码中：graph_data = {
            ('user', 'rate', 'item'): (train_data[:, 0].long(), train_data[:, 1].long()),
            ('item', 'rated by', 'user'): (train_data[:, 1].long(), train_data[:, 0].long())
        }
        graph = dgl.heterograph(graph_data)
        category_tensor = torch.tensor(list(self.category_dic.values()), dtype = torch.long).unsqueeze(1)
        graph.ndata['category'] = {'item': category_tensor, 'user': torch.zeros(self.user_number, 1) - 1}直接这样给item添加category信息会不会物品id和类别并不匹配，造成类别信息添加混乱的情况，就例如item1 的category添加给1550号item了？

**Comment by YangLiangwei** [comment]
item 的category 信息是直接存在 item_category.txt文件里面的，第一列是item id，第二列是category id，和训练集里面的顺序没有关系
