### ISSUE TITLE
As the Beauty dataset

### ISSUE THREAD

**Issue by LayneChai** [YangLiangwei/DGRec#2]
你好，我尝试使用Beauty数据集来跑训练，最后的结果和论文中显示的结果差别有点大，想问一下针对Beauty数据集，模型是有什么调整吗？

**Comment by YangLiangwei** [comment]
您好，模型是没有调整的，针对不同的数据集超参数影响是很大的，可以试试
python main.py --dataset Beauty --lr 0.05 --weight_decay 1e-5 --beta_class 0.975
我这边的结果就比较接近了，针对DGRec方法， beta_class的影响是很大的，需要细致的调整

**Comment by LayneChai** [comment]
> python main.py --dataset Beauty --lr 0.05 --weight_decay 1e-5 --beta_class 0.975

谢谢
