### ISSUE TITLE
关于层注意力

### ISSUE THREAD

**Issue by HBUhss** [YangLiangwei/DGRec#7]
非常抱歉，我没太看懂论文层注意力图中的意思。是衣服和手表被person1喜欢，电脑被person2喜欢，耳机被person喜欢。然后person1可能喜欢项链？person2可能喜欢电话？person可能喜欢书籍？再将这样的推给最下面的person吗？

**Comment by YangLiangwei** [comment]
Layer attention 的设计是为了让center user直接access到higher-order的collaborative filtering的信息，高阶neighborhood信息提供了用户可能会买的东西。这里就是直接把高阶的representation attention encode到最下面的person的representation上
