### ISSUE TITLE
数据集请教

### ISSUE THREAD

**Issue by ahukmr** [YangLiangwei/DGRec#8]
作者您好，我想用您的模型跑其他数据集的话，例如ml-1m或者yelp数据集，您代码中的数据集的划分是按照每个用户的交互记录按照6：2：2的比例进行划分的吗，就算例如一个用户有10个交互，六个作为训练集，2个作为验证机，2个作为测试集进行划分的吗？
另外，您论文中给的数据集是对用户和物品id进行remap 的编码的吗？
不好意思，我的问题可能有点多，期待的带您的回答！谢谢

**Comment by YangLiangwei** [comment]
对的，数据集划分按照每个用户交互记录划分
是对id进行remap的编码
